export const CHECKING_AUTH_STATUS = "CHECKING_AUTH_STATUS";

export const SEARCH_STATE_INPUT = "SEARCH_STATE_INPUT";
export const SEARCH_STATE_RESULT = "SEARCH_STATE_RESULT";
export const SEARCH_STATE_INVALID = "SEARCH_STATE_INVALID";
export const SEARCH_STATE_CHECKING = "SEARCH_STATE_CHECKING";

export const SEARCH_TYPE_PRODUCT = "products";
export const SEARCH_TYPE_SHOP = "shops";

export const ITEMS_COLLECTION = "Items";
export const SHOPS_COLLECTION = "Owners";

export const MAXIMUM_DELIVERY_DISTANCE_MILES = 13; // 20KM
