export const CHECKING_AUTH_STATUS = "CHECKING_AUTH_STATUS";

export const SEARCH_STATE_INPUT = "SEARCH_STATE_INPUT";
export const SEARCH_STATE_RESULT = "SEARCH_STATE_RESULT";
export const SEARCH_STATE_INVALID = "SEARCH_STATE_INVALID";
export const SEARCH_STATE_CHECKING = "SEARCH_STATE_CHECKING";

export const SHOP_COLLECTION = "SHOP_COLLECTION";
export const PRODUCT_COLLECTION = "PRODUCT_COLLECTION";
